// Seth: 
// Starts off the project by making the folder(by doing the proper setup that we were taught)
// and the database server in Atlas

// Server Folder:
// Creates the  library.models.js 
// Creates the server.js 

// Client Folder:
// Create the App.jsx
// Creates the Home/view_books page


// Antwain:
// Server Folder:
// creates the  library.controller.js 

// Client Folder:
// Creates the login/user page 
// Creates the view Profile Page 
// if necessary (Make changes to the App.jsx)



// Mairen:
// Server Folder:
// creates the library.routes.js


// Client Folder:
// creates the Header 
// Creates the review page 
// if necessary (Make changes to the App.jsx)

